REQ_TEMP = 80

(
    HOT_WATER_RLY,
    COLD_WATER_RLY,
    DRAIN_RLY,
    LYE_RLY,
    LYE_RECIRCULATION_RLY,
    WATER_RECIRCULATION_RLY,
    AIR_RLY,
    CO2_RLY
) = range(100, 108)

RELAYS_REG_ADDR = 101
ULED_REG_ADDR = 20
DIGITAL_OUTPUT_REG_ADDR = 1

ON = 1
OFF = 0

MODBUS_ADDR = 'localhost'
MODBUS_PORT = 5020
TUNNEL_REMOTE_ADDR = '192.168.2.2'
TUNNEL_LOCAL_PORT = 5020
TUNNEL_REMOTE_BIND_PORT = 502
DEFAULT_PRIO = 10
