REQ_TEMP = 80

(
    HOT_WATER_RLY,
    COLD_WATER_RLY,
    DRAIN_RLY,
    LYE_RLY,
    LYE_RECIRCULATION_RLY,
    WATER_RECIRCULATION_RLY,
    AIR_RLY,
    CO2_RLY
) = range(100, 108)

ON = 1
OFF = 0

RESET_RLY_STATES = {
    HOT_WATER_RLY: OFF,
    COLD_WATER_RLY: OFF,
    DRAIN_RLY: OFF,
    LYE_RLY: OFF,
    LYE_RECIRCULATION_RLY: OFF,
    WATER_RECIRCULATION_RLY: OFF,
    CO2_RLY: OFF
}


MODBUS_ADDR = '127.0.0.1'
DEFAULT_PRIO = 10
