sudo: false
dist: xenial
language: python
python:
  - "2.7"
  - "3.7"
  - "3.8"
install: pip install tox-travis -r requirements-dev.txt
script: tox
jobs:
  include:
    - name: pre-commit
      python: 3.8
      env: TOXENV=pre-commit
